/*
 * HmGithubCopilotChatWeb v 1.0.0.5
 *
 * Copyright (c) 2025 Akitsugu Komiyama
 * under the MIT License
 */


hidemaruversion "9.39.99";

jsmode  @"WebView2\HmGithubCopilotChatWeb";

js {

// ------------- 会話エンジンの設定項目 -------------

const baseUrl = "https://github.com/copilot";

const renderPaneCustomParam = {
    place: "rightside",            // leftside | rightside | upside | downside
    size: 900,                     // 左や右の配置の時は、横幅のこと。上や下の配置の時は縦幅のこと。
};

const isOneAtTimeAIRenderPane = 1; // AI関連のレンダリング枠は(他の種類のAIも含め)１つだけにする。(複数起動しそうになると、前のものが閉じる）

// --------------------------------------------------

const renderPaneTargetName = "HmGithubCopilotChatWeb";
    
const currentMacroDirectory = currentmacrodirectory();

const script = hidemaru.loadTextFile(currentMacroDirectory + "\\HmConvAIWeb.js");
eval(script);

// ２回目以降に、Github Copilotの返答等を選択した状態で質問した時の挙動が不安感があるので、リフレッシュもしておく。
function secondParamDecorator(baseUrl, text) {
    browserpanecommand({target:"_each", "refresh":1});
}

doMain();

}
