/*
 * HmGithubCopilotChatWeb v 1.1.1.5
 *
 * Copyright (c) 2025 Akitsugu Komiyama
 * under the MIT License
 */

hidemaruversion "9.39.99";

setcompatiblemode 0x08000000;

jsmode  @"WebView2\HmGithubCopilotChatWeb";

js {

// ------------- 会話エンジンの設定項目 -------------

const baseUrl = "https://github.com/copilot";

const renderPaneCustomParam = {
    place: "rightside",            // leftside | rightside | upside | downside
    size: 900,                     // 左や右の配置の時は、横幅のこと。上や下の配置の時は縦幅のこと。
};

const isOneAtTimeAIRenderPane = 1; // AI関連のレンダリング枠は(他の種類のAIも含め)１つだけにする。(複数起動しそうになると、前のものが閉じる）

// --------------------------------------------------

const renderPaneTargetName = "HmGithubCopilotChatWeb";

const currentMacroDirectory = currentmacrodirectory();

const script = hidemaru.loadTextFile(currentMacroDirectory + "\\HmConvAIWeb.js");
eval(script);

var processInfoFocus;
processInfoFocus?.kill();

const [major,minor,build] = hidemaruversion().split(".");

// v9.50β4以降では、フォーカスに比較的自由に当てられる
if (version() >= 950 && build >= 4) {
    function onPrevKeySendDecorator() {
        
        try {
            // Copilotのインプット枠へのフォーカス。手堅いが将来変更になるかも。これがなくても一応はuseInputTransferだけでフォーカスするハズ
            browserpanecommand({target:"_each", focusinputfield:'#copilot-chat-textarea'});
        } catch(e) {
        }
    }
} else {
    // InputFieldへのフォーカスに失敗したらリフレッシュ
    // (これでGithub Copilotが自動で Input フィールドにフォーカスを移動してくれる)
    function focusInputFailDecorator() {
        browserpanecommand({target:"_each", "refresh":1});
    }
}




doMain();

}
